spring:
  datasource:
    url: jdbc:mysql://mymysql:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      jdbc.time_zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
          - threaddump
          - prometheus # 추가

  endpoint:
    health:
      show-details: ALWAYS
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

  info:
    env:
      enabled: true

# 별도 포트를 사용하려면 주석 해제 후 필요한 포트로 설정
  server:
    port: 9091

info:
  app:
    name: "My Spring Boot Application"
    version: "1.0.0"
  team: "My Dev Team"
