name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload start.sh file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.201.30.235
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "start.sh"
          target: "/home/ec2-user/"
          debug: true

      - name: Upload jar file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 43.201.30.235
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "build/libs/todoApp-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"
          debug: true
      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 43.201.30.235
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          sync: false
          script: |
            mv build/libs/todoApp-0.0.1-SNAPSHOT.jar .
            chmod 755 start.sh
            ./start.sh